from .tokens import TokenType

EL_KEYWORDS = {
    "ΔΗΛΩΣΕ": TokenType.DECLARE,
    "ΩΣ": TokenType.AS,
    "ΑΡΙΘΜΟΣ": TokenType.NUMBER_TYPE,
    "ΑΚΕΡΑΙΟΣ": TokenType.INTEGER_TYPE,
    "ΔΕΚΑΔΙΚΟΣ": TokenType.DECIMAL_TYPE,
    "ΚΕΙΜΕΝΟ": TokenType.TEXT_TYPE,
    "ΛΙΣΤΑ": TokenType.LIST_TYPE,
    "ΛΟΓΙΚΟΣ": TokenType.BOOLEAN_TYPE,
    "ΑΛΗΘΗΣ": TokenType.TRUE,
    "ΨΕΥΔΗΣ": TokenType.FALSE,
    "ΚΕΝΟ": TokenType.NULL,
    "ΕΜΦΑΝΙΣΕ": TokenType.DISPLAY,
    "ΠΕΣ_ΜΟΥ": TokenType.INPUT,
    "ΑΝ": TokenType.IF,
    "ΤΟΤΕ": TokenType.THEN,
    "ΕΣΤΩ": TokenType.ELSE_IF,
    "ΑΛΛΙΩΣ": TokenType.ELSE,
    "ΤΕΛΟΣ_ΑΝ": TokenType.END_IF,
    "ΓΙΑ": TokenType.FOR,
    "ΑΠΟ": TokenType.FROM,
    "ΜΕΧΡΙ": TokenType.TO,
    "ΤΕΛΟΣ_ΓΙΑ": TokenType.END_FOR,
    "ΟΣΟ": TokenType.WHILE,
    "ΤΕΛΟΣ_ΟΣΟ": TokenType.END_WHILE,
    "ΣΥΝΑΡΤΗΣΗ": TokenType.FUNCTION,
    "ΤΕΛΟΣ_ΣΥΝΑΡΤΗΣΗ": TokenType.END_FUNCTION,
    "ΕΠΙΣΤΡΕΨΕ": TokenType.RETURN,
    "ΔΙΑΚΟΨΕ": TokenType.BREAK,
    "ΔΙΑΚΟΠΗ": TokenType.LOOP_BREAK,
    "ΤΕΡΜΑΤΙΣΕ": TokenType.TERMINATE,
    "ΚΑΙ": TokenType.AND,
    "Ή": TokenType.OR,
    "ΟΧΙ": TokenType.NOT,
    "ΠΡΟΣΘΕΣΕ_ΣΤΗ_ΛΙΣΤΑ": TokenType.LIST_APPEND,
    "ΜΕΤΑΤΡΕΨΕ_ΣΕ_ΛΟΓΙΚΟ": TokenType.TO_BOOLEAN,
    "ΜΗΚΟΣ": TokenType.LIST_LENGTH,
    "ΔΟΜΗ": TokenType.STRUCT_TYPE,
    "HTTP_ΑΠΑΝΤΗΣΗ": TokenType.HTTP_RESPONSE_TYPE,
    "ΣΤΑΘΕΡΑ": TokenType.CONSTANT,
    "ΕΙΣΑΓΕ": TokenType.IMPORT,
    "ΣΧΟΛΙΟ": TokenType.COMMENT,
    "ΣΕ": TokenType.IN
}
