from .tokens import TokenType

EN_KEYWORDS = {
    "DECLARE": TokenType.DECLARE,
    "AS": TokenType.AS,
    "NUMBER": TokenType.NUMBER_TYPE,
    "INTEGER": TokenType.INTEGER_TYPE,
    "DECIMAL": TokenType.DECIMAL_TYPE,
    "TEXT": TokenType.TEXT_TYPE,
    "LIST": TokenType.LIST_TYPE,
    "BOOLEAN": TokenType.BOOLEAN_TYPE,
    "TRUE": TokenType.TRUE,
    "FALSE": TokenType.FALSE,
    "NULL": TokenType.NULL,
    "DISPLAY": TokenType.DISPLAY,
    "INPUT": TokenType.INPUT,
    "IF": TokenType.IF,
    "THEN": TokenType.THEN,
    "ELSE_IF": TokenType.ELSE_IF,
    "ELSE": TokenType.ELSE,
    "END_IF": TokenType.END_IF,
    "FOR": TokenType.FOR,
    "FROM": TokenType.FROM,
    "TO": TokenType.TO,
    "END_FOR": TokenType.END_FOR,
    "WHILE": TokenType.WHILE,
    "END_WHILE": TokenType.END_WHILE,
    "FUNCTION": TokenType.FUNCTION,
    "END_FUNCTION": TokenType.END_FUNCTION,
    "RETURN": TokenType.RETURN,
    "BREAK": TokenType.BREAK,
    "TERMINATE": TokenType.TERMINATE,
    "AND": TokenType.AND,
    "OR": TokenType.OR,
    "NOT": TokenType.NOT,
    "APPEND": TokenType.LIST_APPEND,
    "TO_BOOLEAN": TokenType.TO_BOOLEAN,
    "LENGTH": TokenType.LIST_LENGTH,
    "STRUCT": TokenType.STRUCT_TYPE,
    "HTTP_RESPONSE": TokenType.HTTP_RESPONSE_TYPE,
    "CONST": TokenType.CONSTANT,
    "IMPORT": TokenType.IMPORT,
    "COMMENT": TokenType.COMMENT
}
